### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by forevermatt** [silinternational/simplesamlphp-module-expirychecker#3]
Update the view templates, etc. so that the page can be displayed in the main languages we support.

**Comment by forevermatt** [comment]
One useful tool for formatting messages (especially dates) is the [msgfmt_format_message](http://php.net/manual/en/messageformatter.formatmessage.php) (or [MessageFormatter](http://php.net/MessageFormatter)) feature in PHP.

For reference (since it wasn't immediately apparent for me), if you scroll down [this page](http://icu-project.org/apiref/icu4c/classMessageFormat.html#details) to the table, you will see several codes available to use in your messages.

Example:

    echo msgfmt_format_message(
        'en',
        'Today is {0,date,long}',
        [time()]
    );

That will output the following:

    Today is July 12, 2017

**Comment by briskt** [comment]
The [material module](https://github.com/silinternational/ssp-base?tab=readme-ov-file#material-module) adds translation strings.
